### ISSUE TITLE
.gitignore должен быть в корневой папке

### ISSUE THREAD

**Issue by coursar** [dilshod-ship-it/purchase#1]
https://github.com/dilshod-ship-it/purchase/blob/bf626e58b308ddf0d14c4204fc18ce90c954a13b/src/.gitignore#L1-L44

**Comment by dilshod-ship-it** [comment]
Извините Ильназ, не получается commit сделать

**Comment by dilshod-ship-it** [comment]
все ошибки исправил и отправил, извините git немного глючит

**Comment by dilshod-ship-it** [comment]
purchase отправил новым проектом с названием purchase-DZ
